spring.application.name=ToTwo
#spring.datasource.url=jdbc:postgresql://localhost:5432/ToTwo
#spring.datasource.username=ToTwo
#spring.datasource.password=1997jk
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=this_is_my_super_secret_key_1234567890
server.port=${PORT:8080}